# Generated by Django 5.2.8 on 2025-12-16 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('categoryID', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Event Categories',
                'db_table': 'eventCategory',
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('organizerID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255)),
                ('contactNum', models.CharField(max_length=20, unique=True)),
                ('website', models.URLField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'organizer',
            },
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('ticketTypeID', models.AutoField(primary_key=True, serialize=False)),
                ('ticket_type', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'ticketType',
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('venueID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
            ],
            options={
                'db_table': 'venue',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('remaining_capacity', models.IntegerField()),
                ('rundown', models.TextField(blank=True)),
                ('materials', models.TextField(blank=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.eventcategory', verbose_name='Event Category')),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='EventCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
            options={
                'verbose_name_plural': 'Event Customers',
                'db_table': 'eventCustomer',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='customers',
            field=models.ManyToManyField(related_name='attended_events', through='events.EventCustomer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EventDateTime',
            fields=[
                ('eventDateTimeID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
            ],
            options={
                'verbose_name_plural': 'Event Date Times',
                'db_table': 'eventDateTime',
                'ordering': ['date', 'startTime'],
                'unique_together': {('date', 'startTime', 'endTime')},
            },
        ),
        migrations.AddField(
            model_name='event',
            name='datetime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='events.eventdatetime', verbose_name='Scheduled Time'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organized_events', to='events.organizer', verbose_name='Organizer'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticketID', models.AutoField(primary_key=True, serialize=False)),
                ('rowNum', models.IntegerField()),
                ('seatNum', models.IntegerField()),
                ('purchaseDateTime', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('sold', 'Sold'), ('cancelled', 'Cancelled'), ('checked_in', 'Checked In')], default='reserved', max_length=15)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='events.event')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='events.tickettype')),
            ],
            options={
                'db_table': 'ticket',
                'unique_together': {('event', 'rowNum', 'seatNum')},
            },
        ),
        migrations.AddField(
            model_name='eventcustomer',
            name='ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_record', to='events.ticket'),
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='events.venue', verbose_name='Venue'),
        ),
        migrations.AlterUniqueTogether(
            name='eventcustomer',
            unique_together={('event', 'customer', 'ticket')},
        ),
    ]
