# Generated by Django 5.2.8 on 2025-12-16 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tickettype",
            name="eventID",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ticket_types",
                to="events.event",
            ),
            preserve_default=False,
        ),
    ]
