# Generated by Django 5.2.8 on 2025-12-16 13:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_tickettype_eventid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tickettype",
            old_name="eventID",
            new_name="event",
        ),
    ]
