# Generated by Django 5.2.8 on 2025-12-16 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rename_eventid_tickettype_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickettype',
            old_name='type',
            new_name='tickettype',
        ),
    ]
