# Generated by Django 5.2.8 on 2025-11-28 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerID', models.AutoField(primary_key=True, serialize=False)),
                ('fName', models.CharField(max_length=100)),
                ('lName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255)),
                ('hashedPassword', models.CharField(max_length=255)),
                ('phoneNum', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('categoryID', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Event Categories',
                'db_table': 'eventCategory',
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('organizerID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255)),
                ('contactNum', models.CharField(max_length=20, unique=True)),
                ('website', models.URLField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'organizer',
            },
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('ticketTypeID', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('zone', models.CharField(max_length=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'ticketType',
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('venueID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
            ],
            options={
                'db_table': 'venue',
            },
        ),
        migrations.RemoveField(
            model_name='event',
            name='id',
        ),
        migrations.AddField(
            model_name='event',
            name='eventID',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='EventDateTime',
            fields=[
                ('eventDateTimeID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
            ],
            options={
                'verbose_name_plural': 'Event Date Times',
                'db_table': 'eventDateTime',
                'ordering': ['date', 'startTime'],
                'unique_together': {('date', 'startTime', 'endTime')},
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticketID', models.AutoField(primary_key=True, serialize=False)),
                ('rowNum', models.IntegerField()),
                ('seatNum', models.IntegerField()),
                ('purchaseDateTime', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('sold', 'Sold'), ('cancelled', 'Cancelled'), ('checked_in', 'Checked In')], default='reserved', max_length=15)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='events.event')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='events.tickettype')),
            ],
            options={
                'db_table': 'ticket',
                'unique_together': {('event', 'rowNum', 'seatNum')},
            },
        ),
    ]
