# Generated by Django 5.2.8 on 2025-11-28 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_customer_eventcategory_organizer_tickettype_venue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.customer')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_record', to='events.ticket')),
            ],
            options={
                'verbose_name_plural': 'Event Customers',
                'unique_together': {('event', 'customer', 'ticket')},
            },
        ),
    ]
