# Generated by Django 5.2.8 on 2025-12-16 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rename_type_tickettype_tickettype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickettype',
            old_name='tickettype',
            new_name='ticket_type',
        ),
    ]
