# Generated by Django 5.2.8 on 2025-11-28 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventcustomer'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='eventcustomer',
            table='eventCustomer',
        ),
    ]
