# Generated by Django 5.2.8 on 2025-12-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_rename_tickettype_tickettype_ticket_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='remaining_capacity',
            field=models.IntegerField(default=69),
            preserve_default=False,
        ),
    ]
