# Generated by Django 5.2.8 on 2025-12-16 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_rename_tickettype_tickettype_ticket_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickettype',
            name='event',
        ),
    ]
