# Generated by Django 5.2.8 on 2025-12-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0006_event_remaining_capacity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venue",
            name="address",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="venue",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
