# Generated by Django 5.2.8 on 2025-12-16 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_venue_address_alter_venue_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickettype',
            name='zone',
        ),
    ]
