# Generated by Django 5.2.8 on 2025-12-09 08:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="is_admin",
            new_name="is_staff",
        ),
    ]
